version: '3.1'

services:
  mysql:
    image: mysql:8.0   # or another version you prefer
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: store_D
      MYSQL_USER: cecilhu
      MYSQL_PASSWORD: heihallo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
